{{- if .Values.proxy.ingress.hostName }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: {{- include "dfour-hub.labels" . | nindent 4 }}
    app: {{ template "dfour-hub.name" . }}
  name: dfour-hub-ingress
  namespace: {{ include "release_namespace" . }}
  annotations:
    {{- range $key, $value := .Values.proxy.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  {{- if and .Values.proxy.ingress.ingressClassName (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.proxy.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.proxy.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.proxy.ingress.hostName }}
    secretName: {{ template "dfour-hub.name" . }}-tls-secret
  {{- end }}
  rules:
  - host: {{ .Values.proxy.ingress.hostName }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: dfour-hub-service
            port:
              number: 8443
{{- end }}