apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {{- include "dfour-hub.labels" . | nindent 4 }}
    app: {{ template "dfour-hub.name" . }}
  name: dfour-proxy
  namespace: {{ include "release_namespace" . }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app: {{ template "dfour-hub.name" . }}
  template:
    metadata:
      labels: {{- include "dfour-hub.labels" . | nindent 8 }}
        app: {{ template "dfour-hub.name" . }}
    spec:
      containers:
      - name: dfour-hub
        {{- if .Values.proxy.digest }}
        image: {{ .Values.proxy.image }}:{{ .Values.proxy.tag }}@{{ .Values.proxy.digest }}
        {{- else }}
        image: {{ .Values.proxy.image }}:{{ .Values.proxy.tag }}
        {{- end }}
        imagePullPolicy: IfNotPresent
        env:
        - name: NGINX_SERVER_NAME
          value: "{{ .Values.proxy.ingress.hostName }}"
        - name: NGINX_PORT
          value: "{{ .Values.proxy.port }}"
        - name: NGINX_HUB_UPSTREAM
          value: "{{ .Values.proxy.upstream }}:{{ .Values.hub.port }}"
        - name: NGINX_ACCESS_LOG
          value: "{{ .Values.proxy.accessLog }}"
        - name: NGINX_ERROR_LOG
          value: "{{ .Values.proxy.errorLog }}"
        - name: NGINX_MAX_BODY_SIZE
          value: "{{ .Values.proxy.maxBodySize }}"
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: {{ template "dfour-hub.name" . }}-volume
          mountPath: /var/services
        livenessProbe:
          httpGet:
            host: "{{ .Values.proxy.upstream }}"
            port: 8081
            path: "/gmanage"
          failureThreshold: 1
          periodSeconds: 60
          # Override pod-level terminationGracePeriodSeconds #
          terminationGracePeriodSeconds: 60
      volumes:
      - name: {{ template "dfour-hub.name" . }}-volume
        persistentVolumeClaim:
          claimName: pvc-{{ template "dfour-hub.name" . }}
