apiVersion: v1
kind: Service
metadata:
  labels: {{- include "dfour-hub.labels" . | nindent 4 }}
    app: {{ template "dfour-hub.name" . }}
  name: dfour-hub-service
  namespace: {{ include "release_namespace" . }}
  annotations:
    {{- range $key, $value := .Values.proxy.svc.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
  selector:
    app: {{ template "dfour-hub.name" . }}