nameOverride: ~
storageClassName: "local-device"

hub:
  replicas: 1
  image: registry.gitlab.com/dfour/dfour-hub
  tag: latest
  digest: ~

  memory:
    request: "200Mi"
    limit: "2Gi"

  terminal: linux
  autostart: "YES"
  port: 8081
  debug: false
  https: false

  secretsRef: dfour-hub-secret

  allowedHosts: localhost,django

  municipalitiesUrl: https://datahub.io/cividi/ch-municipalities/r/2.geojson

  email:
    host:
    port:
    tls: true
    from:
  
  admin:
    headerTitle: dføur-hub
    headerColor: "#000000"
  
  screenshot:
    run: YES
    # if set to yes, define schedule
    # * every minute, */5 every 5 minutes
    cronJob: "*"
  
  oidc:
    enabled: false
    rpClientId: ~
    rpClientSecret: ~
    opAuhorizationEndpoint: ~
    opTokenEndpoint: ~
    opUserEndpoint: ~
    opJwksEndpoint: ~
    opLogoutEndpoint: ~
  
celery:
  broker: redis://localhost:6379/0
  backend: redis://localhost:6379/0

proxy:
  replicas: 1
  image: ghcr.io/dfourio/dfour-proxy/dfour-proxy
  tag: main
  digest: ~

  host: ~
  port: 8000
  upstream: django-hub-0

  accessLog: /dev/stdout
  errorLog: /dev/stdout

  maxBodySize: 25M

  svc:
    annotations: {}
  ingress:
    annotations: {}
    hostName: ~



## Specify override namespace, specifically this is useful for using dfour as sub-chart
## and its release namespace is not `dfour`
namespaceOverride: ""
